In [1]:
import numpy as np

# From a Python list
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)



[1 2 3 4 5]


In [2]:
# From a Python tuple
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)


[1 2 3 4 5]


In [3]:
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
ones_array = np.ones((3, 3))
print(ones_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
empty_array = np.empty((3, 3))
print(empty_array)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
full_array = np.full((3, 3), 7)
print(full_array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
arange_array = np.arange(0, 10, 2)
print(arange_array)


[0 2 4 6 8]


In [8]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)


[0.   0.25 0.5  0.75 1.  ]


In [9]:
#array indexing and slicing
#1d
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[0])  
print(a[4])  


1
5


In [10]:
#2d
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 0])  
print(b[1, 2])  


1
6


In [11]:
#3d
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c[0, 0, 0])  
print(c[1, 1, 1])  


1
8


In [12]:
#slicing 1d
a = np.array([1, 2, 3, 4, 5])
print(a[1:4])  
print(a[:3])   
print(a[3:])   
print(a[::2])  


[2 3 4]
[1 2 3]
[4 5]
[1 3 5]


In [13]:
#2d
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0:2, 1:3])  
print(b[:, 1])     
print(b[1, :])      
print(b[::2, ::2])  
                


[[2 3]
 [5 6]]
[2 5 8]
[4 5 6]
[[1 3]
 [7 9]]


In [14]:
#Array manipulation
#reshape
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_a = a.reshape((3, 2))
print(reshaped_a)



[[1 2]
 [3 4]
 [5 6]]


In [15]:
#flattend
flattened_a = a.flatten()
print(flattened_a)


[1 2 3 4 5 6]


In [16]:
#transpose
transposed_a = a.transpose()
print(transposed_a)


[[1 4]
 [2 5]
 [3 6]]


In [19]:
#concatenate
b = np.array([[7, 8, 9]])
concatenated_a = np.concatenate((a, b), axis=0)
print(concatenated_a)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#splitting the arrays
d = np.array([1, 2, 3, 4, 5, 6])
split_d = np.split(d, 3)
print(split_d)



[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
#append
f = np.array([1, 2, 3])
appended_f = np.append(f, [4, 5, 6])
print(appended_f)



[1 2 3 4 5 6]


In [25]:
#insert
g = np.array([1, 2, 3])
inserted_g = np.insert(g, 1, [9, 10])
print(inserted_g)



[ 1  9 10  2  3]


In [26]:
#delete
h = np.array([1, 2, 3, 4, 5])
deleted_h = np.delete(h, [1, 3])
print(deleted_h)



[1 3 5]


In [27]:
#Mathematical operation
#Arithmetc operations
import numpy as np

# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Addition
sum_ab = np.add(a, b)
print("Sum:", sum_ab)

# Subtraction
diff_ab = np.subtract(a, b)
print("Difference:", diff_ab)

# Multiplication
prod_ab = np.multiply(a, b)
print("Product:", prod_ab)

# Division
quot_ab = np.divide(a, b)
print("Quotient:", quot_ab)    

# Exponentiation
exp_a = np.exp(a)
print("Exponential:", exp_a)

# Square root
sqrt_a = np.sqrt(a)
print("Square Root:", sqrt_a)



Sum: [ 6  8 10 12]
Difference: [-4 -4 -4 -4]
Product: [ 5 12 21 32]
Quotient: [0.2        0.33333333 0.42857143 0.5       ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Square Root: [1.         1.41421356 1.73205081 2.        ]


In [28]:
#Aggregate functions
# Create an array
c = np.array([1, 2, 3, 4, 5])

# Sum
sum_c = np.sum(c)
print("Sum:", sum_c)

# Mean
mean_c = np.mean(c)
print("Mean:", mean_c)

# Standard deviation
std_c = np.std(c)
print("Standard Deviation:", std_c)

# Minimum
min_c = np.min(c)
print("Minimum:", min_c)

# Maximum
max_c = np.max(c)
print("Maximum:", max_c)




Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Minimum: 1
Maximum: 5


In [29]:
#linear algebra
# Create a 2x2 matrix
A = np.array([[1, 2], [3, 4]])

# Inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
#Determinant
import numpy as np
A = np.array([[1, 2], [3, 4]])

# Compute the determinant of matrix A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)


Determinant of A: -2.0000000000000004


In [31]:
#eigenvalues and eigenvectors
import numpy as np

# Create a 2x2 matrix A
A = np.array([[1, 2], [3, 4]])

# Compute the eigenvalues and eigenvectors of matrix A
eigvals, eigvecs = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues:", eigvals)

# Print the eigenvectors
print("Eigenvectors:\n", eigvecs)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [32]:
#Matrix multiplication
# Matrix multiplication
B = np.array([[5, 6], [7, 8]])
matmul_AB = np.matmul(A, B)
print("Matrix Multiplication of A and B:\n", matmul_AB)


Matrix Multiplication of A and B:
 [[19 22]
 [43 50]]


In [33]:
#Random number #rand()
import numpy as np

# Generate a single random number
random_number = np.random.rand()
print("Single random number:", random_number)

# Generate a 1D array of random numbers
random_array_1d = np.random.rand(5)
print("1D array of random numbers:", random_array_1d)

# Generate a 2D array of random numbers
random_array_2d = np.random.rand(3, 4)
print("2D array of random numbers:\n", random_array_2d)


Single random number: 0.24621084261865955
1D array of random numbers: [0.7825009  0.75018742 0.29843686 0.42987531 0.46391464]
2D array of random numbers:
 [[0.14954854 0.98952633 0.01916511 0.73447044]
 [0.3158708  0.87913617 0.71124743 0.21434116]
 [0.90366665 0.35684235 0.55594948 0.21943733]]


In [34]:
# Generate a single random integer
#randint()
random_int = np.random.randint(1, 10)
print("Single random integer:", random_int)

# Generate a 1D array of random integers
random_int_array_1d = np.random.randint(1, 10, size=5)
print("1D array of random integers:", random_int_array_1d)

# Generate a 2D array of random integers
random_int_array_2d = np.random.randint(1, 10, size=(3, 4))
print("2D array of random integers:\n", random_int_array_2d)


Single random integer: 8
1D array of random integers: [5 6 9 2 9]
2D array of random integers:
 [[4 8 6 4]
 [3 9 4 9]
 [7 1 7 1]]


In [37]:
#choice
# Define an array to sample from
array = np.array([1, 2, 3, 4, 5])

# Generate a single random sample
random_sample = np.random.choice(array)
print("Single random sample:", random_sample)

# Generate multiple random samples (with replacement)
random_samples_with_replacement = np.random.choice(array, size=3)
print("Random samples with replacement:", random_samples_with_replacement)

# Generate multiple random samples (without replacement)
random_samples_without_replacement = np.random.choice(array, size=3, replace=False)
print("Random samples without replacement:", random_samples_without_replacement)


Single random sample: 1
Random samples with replacement: [1 5 2]
Random samples without replacement: [2 1 3]


In [38]:
#statistical performance
#mean
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
print("Mean:", mean)


Mean: 3.0


In [39]:
#median
median = np.median(data)
print("Median:", median)


Median: 3.0


In [40]:
#standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)


Standard Deviation: 1.4142135623730951


In [41]:
#variance
variance = np.var(data)
print("Variance:", variance)


Variance: 2.0


In [42]:
#Maximum and minimum values in the array
min_value = np.min(data)
max_value = np.max(data)
print("Min:", min_value)
print("Max:", max_value)


Min: 1
Max: 5
